# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: GitHub Metrics
on:
  # Schedule updates (each day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: alex-kattathra-johnson
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_leetcode: yes
          plugin_leetcode_user: alex-kattathra-johnson
          plugin_leetcode_sections: solved, skills, recent
          config_timezone: America/Chicago
